#!/bin/sh

if [[ "$(git config --get my.interactive)" = yes ]];then
    # git -c my.interactive=yes commit

    exec < /dev/tty deno run --allow-net --allow-write --allow-run --allow-read .githooks/commitHook.ts
fi

