version: v1

labels:
  - label: "o.x.x"
    sync: true
    matcher:
      commits: ":`o.x.x`\\(.*\\): .*"

  - label: "x.o.x"
    sync: true
    matcher:
      commits: ":`x.o.x`\\(.*\\): .*"

  - label: "x.x.o"
    sync: true
    matcher:
      commits: ":`x.x.o`\\(.*\\): .*"

  - label: "x.x.x"
    sync: true
    matcher:
      commits: ":`x.x.x`\\(.*\\): .*"
