name: "Quality check"

runs:
  using: "composite"
  steps:
    - name: "Checkout"
      uses: actions/checkout@v3

    - name: Install
      shell: bash
      run: pnpm install

    - name: Quality check
      shell: bash
      run: pnpm run qualityCheck
