name: "Quality check"

runs:
  using: "composite"
  steps:
    - name: "Checkout"
      uses: actions/checkout@v3

    - name: Install
      shell: bash
      run: npm i --legacy-peer-deps

    - name: Quality check
      shell: bash
      run: npm run qualityCheck
