import type { NextPage } from "next";
// import NextTopLoader from "nextjs-toploader";

export const dynamic = "force-dynamic";
export const revalidate = 0;
// export const fetchCache = "force-no-store";
// export const fetchCache = "only-no-store";
export const fetchCache = "default-no-store";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

type Props = {
  children: React.ReactNode;
};
const Layout: NextPage<Props> = (props) => (
  <html lang="ja">
    <body>
      {/* <NextTopLoader /> */}
      {props.children}
    </body>
  </html>
);

export default Layout;
