import type { NextPage } from "next";
import NextTopLoader from "nextjs-toploader";
import { Provider } from "~/ui/provider";

export const dynamic = "force-dynamic";
export const revalidate = 0;

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

type Props = {
  children: React.ReactNode;
};
const Layout: NextPage<Props> = (props) => (
  <html lang="ja">
    <body>
      <NextTopLoader />
      <Provider>{props.children}</Provider>
    </body>
  </html>
);

export default Layout;

// TODO チャクラ 適用
