on:
  pull_request:
    branches: main

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: fuxingloh/multi-labeler@main
