on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16.x"]
    name: Node ${{ matrix.node }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Quality check
        uses: ./.github/actions/qualityCheck

      - name: Release
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
