on:
  push:
    branches:
      - main
jobs:
  release:
    # 基本部分
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16.x"]
    name: Node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        run: yarn

      - name: Quality check
        run: yarn qualityCheck

      # カスタム
      - name: Release
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
